### ISSUE TITLE
Error on initial execution

### ISSUE THREAD

**Issue by SlimeDog** [Dart2112/WarpPoint#1]
Spigot 1.12.2 latest
WarpPoint 1.1.1

Only one warppoint exists, owned by me (admin user).
```
UUID: {elided}
UserName: {elided}
Permission: warppoint.admin
OfflineSince: 1516978301397
Warps:
  list:
  - blackdog_faction
  blackdog_faction:
    location:
      ==: org.bukkit.Location
      world: world_blackdog
      x: 415.5
      y: 110.0625
      z: 291.5
      pitch: 0.0
      yaw: -90.0
OnlineSince: 1516978154086
```
I have permission
```
>lp user {elided} permission checkinherits warppoint.admin
[06:56:50 INFO]: [LP] {elided} has permission warppoint.admin set to true in context global. (inherited from admin)
```

After server restart and connect (on test server, so I am the only player connected), execute
```
/warp blackdog faction
```
with the result
```
An internal error occurred while attempting to perform this command
```
and console/log error
```
[06:49:35 INFO]: {elided} issued server command: /warp blackdog faction
[06:49:35 ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v6.2.2-SNAPSHOT;1712-3a332fd
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar-2018-01-24-1921:git-Spigot-4bd94dc-c765646]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar-2018-01-24-1921:git-Spigot-4bd94dc-c765646]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar-2018-01-24-1921:git-Spigot-4bd94dc-c765646]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar-2018-01-24-1921:git-Spigot-4bd94dc-c765646]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:519) [spigot-1.12.2.jar-2018-01-24-1921:git-Spigot-4bd94dc-c765646]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity.teleport(CraftEntity.java:271) [spigot-1.12.2.jar-2018-01-24-1921:git-Spigot-4bd94dc-c765646]
        at net.lapismc.warppoint.commands.WarpPointWarp.warp(WarpPointWarp.java:127) [WarpPoint-1.1.1.jar:?]
        at net.lapismc.warppoint.WarpPointCommands.onCommand(WarpPointCommands.java:55) [WarpPoint-1.1.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.12.2.jar-2018-01-24-1921:git-Spigot-4bd94dc-c765646]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:443) [EssentialsX-2.0.1-b588.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:432) [EssentialsX-2.0.1-b588.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.12.2.jar-2018-01-24-1921:git-Spigot-4bd94dc-c765646]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.12.2.jar-2018-01-24-1921:git-Spigot-4bd94dc-c765646]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) [spigot-1.12.2.jar-2018-01-24-1921:git-Spigot-4bd94dc-c765646]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot-1.12.2.jar-2018-01-24-1921:git-Spigot-4bd94dc-c765646]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2.jar-2018-01-24-1921:git-Spigot-4bd94dc-c765646]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar-2018-01-24-1921:git-Spigot-4bd94dc-c765646]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar-2018-01-24-1921:git-Spigot-4bd94dc-c765646]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar-2018-01-24-1921:git-Spigot-4bd94dc-c765646]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar-2018-01-24-1921:git-Spigot-4bd94dc-c765646]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar-2018-01-24-1921:git-Spigot-4bd94dc-c765646]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar-2018-01-24-1921:git-Spigot-4bd94dc-c765646]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar-2018-01-24-1921:git-Spigot-4bd94dc-c765646]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar-2018-01-24-1921:git-Spigot-4bd94dc-c765646]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[spigot-1.12.2.jar-2018-01-24-1921:git-Spigot-4bd94dc-c765646]
        at com.sk89q.worldguard.bukkit.RegionQuery.getApplicableRegions(RegionQuery.java:91) ~[?:?]
        at com.sk89q.worldguard.bukkit.listener.WorldGuardPlayerListener.onPlayerTeleport(WorldGuardPlayerListener.java:366) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor248.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar-2018-01-24-1921:git-Spigot-4bd94dc-c765646]
        ... 26 more
```
An immediate subsequent execution
```
/warp blackdog
```
is performed without error, and subsequent executions
```
/warp blackdog faction
```
are performed without error.

If the initial invocation is
```
/warp blackdog
```
no errors occur.

**Comment by Dart2112** [comment]
Not sure why this happens as I have never experienced it. But I'll look into it

**Comment by Dart2112** [comment]
Sorry, just went to do some work on WarpPoint and fix this while I was at it. This is an issue with world guard. I'll see if it is something I can fix but I doubt it

**Comment by Dart2112** [comment]
The line of my code that is referenced is where we teleport the player to a location, I believe it might have something to do with loading the location on the first run but then its available for the second. I'll do some more investigating

**Comment by Dart2112** [comment]
I believe I have fixed the issue, you can compile the code form the latest commit and test it your self if you wish. I will be testing it later today and update Warp Point if it does work.
